Knn clustering
FNLCR-DMAP/SCSAWorkflow pull request #250
Opened 2024-10-26 16:38 UTC by oeldaghar

2024-11-06 16:32 UTC, georgezakinih requested changes
@oeldaghar, Thanks for putting the PR. I shared with you few comments. It's a good first pass for adding functionality to SPAC. We can also schedule a code review session if you want to discuss these comments.

2024-11-06 16:32 UTC, georgezakinih commented on src/spac/transformations.py
> +        The variables that would be included in creating the phenograph
@oeldaghar, the cluster is not phenograph

2024-11-06 16:32 UTC, georgezakinih commented on src/spac/transformations.py
> +        The layer to be used in calculating the phengraph clusters.
@oeldaghar, same comment about phenograph

2024-11-06 16:32 UTC, georgezakinih commented on src/spac/transformations.py
> +    k : int, optional
@oeldaghar, is it creating a graph? I believe it is a ball tree.

2024-11-06 16:32 UTC, georgezakinih commented on src/spac/transformations.py
> +        raise ValueError("`k` must be a positive integer")
@oeldaghar , please add in the error message the received value as it is a hint for the user.

2024-11-06 16:32 UTC, georgezakinih commented on src/spac/transformations.py
> +        raise ValueError("All cells are labeled. Please provide a mix of labeled and unlabeled data.")
@oeldaghar, please mention the "annotation" that has been used. So something like: f'All cells are labeled in the annotation "{annotation". ..."

2024-11-06 16:32 UTC, georgezakinih commented on src/spac/transformations.py
> +        raise ValueError("No cells are labeled. Please provide a mix of labeled and unlabeled data.")
@oeldaghar, same as the above comment.

2024-11-06 16:32 UTC, georgezakinih commented on src/spac/transformations.py
> +    annotation_labeled = np.array(annotation_data[annotation_mask], dtype=int)
What is the values in adata.obs[annotation] is a string?

2024-11-06 16:32 UTC, georgezakinih commented on src/spac/transformations.py
> +    knn_predict = classifier.predict(data)
@oeldaghar, why predict on the data that was already labeled?

2024-11-06 16:32 UTC, georgezakinih commented on src/spac/transformations.py
> +    adata.uns["knn_features"] = features
@oeldaghar, suggestion, instead of adata.uns["knn_features"], use adata.uns[output_annotation]

2024-11-06 16:32 UTC, georgezakinih commented on tests/test_transformations/test_knn_clustering.py
> +    def setUp(self):
@oeldaghar, can we start with a very simple case of minimum number of points (e.g., 4 points, two labeled and two unlabled, with K=1), then elaborate that use case to cover more corner cases?

2024-11-06 16:32 UTC, georgezakinih commented on tests/test_transformations/test_knn_clustering.py
> +from sklearn.datasets import load_iris
@oeldaghar, do we need that dataset?

2024-11-06 16:32 UTC, georgezakinih commented on tests/test_transformations/test_knn_clustering.py
> +    def test_invalid_k(self):
@oeldaghar, please also check that the appropriate error message is generated.

2024-11-06 16:32 UTC, georgezakinih commented on tests/test_transformations/test_knn_clustering.py
> +    def test_layer_none_case(self):
@oeldaghar, I suggest to put that test as part of _select_input_features if that is not already there.

2024-11-06 16:32 UTC, georgezakinih commented on tests/test_transformations/test_knn_clustering.py
> +    def test_trivial_label(self):
@oeldaghar, please check the error message too.

2024-11-06 16:32 UTC, georgezakinih commented on tests/test_transformations/test_knn_clustering.py
> +    def test_associated_features(self):
@oeldaghar, I believe that test is already covered part of _select_input_features.

2024-11-14 23:57 UTC, oeldaghar commented
@akolliegbo could you take a look at this and make the requested changes. we can schedule time to meet if it helps digests the request

2024-12-12 08:13 UTC, closed without merging